### PR TITLE
Fix hubot slack v4 upgrade

### LINKED ISSUE #16: Hackbot broken by hubot-slack v4
See TechNottingham/Hackbot#29

Some work is in progress to fix this but it means the brain data is now a totally invalid source of information.

Using the client's memory data store is an appropriate fix for now but should really be abstracted away somehow so that any version of the client can be used - or perhaps we should just bite the bullet and stick to using the memory store from now on.

### PR DESCRIPTION
**Pull request by Codesleuth**
Basically remove the use of the brain for user information and use the slack adapter client's data store.
Also pads out some typings which will be pulled out at some point.

Fixes #16

### CODE REVIEW

File: src/custom_typings/hubot-slack.d.ts [hunk 1]
```diff
@@ -50,20 +66,28 @@ declare module "hubot-slack" {
     icon_emoji?: string;
   }
 
-  interface SlackBot extends Adapter {
-    client: {
-      rtm: {
-        dataStore: MemoryDataStore;
-      }
+  interface SlackBotClient {
+    rtm: {
```
Comment (hawx) [inline src/custom_typings/hubot-slack.d.ts]: Should this be the same as the `RtmClient` above?

File: src/scripts/create_team.script.ts [hunk 2]
```diff
@@ -3,20 +3,20 @@ import { RobotWithClient } from '../hackbot';
 export default (robot: RobotWithClient) => {
 
   robot.respond(/create team (.*)/i, (response) => {
-    const userId = response.message.user.id;
+    const user = robot.adapter.client.rtm.dataStore.getUserById(response.message.user.id);
```
Comment (hawx) [inline src/scripts/create_team.script.ts:6]: Since this is now everywhere could the dataStore be wrapped/exposed at a higher level or something? So we instead have

``` typescript
const user = robot.dataStore.getUserById(response.message.user.id);
```

This would also prevent things from breaking as much when they change everything again.

Comment (Codesleuth) [reply src/scripts/create_team.script.ts:6]: Yeh totally. I have a plan to split it out so the scripts are injected with it as a dependency rather than relying on the robot. I think it's probably best to leave this how it is and make this change separately though.

Comment (hawx) [reply src/scripts/create_team.script.ts:6]: :+1:

File: src/custom_typings/hubot-slack.d.ts (hunk 1 above)
Comment (Codesleuth) [reply src/custom_typings/hubot-slack.d.ts]: Indeed it is! I just need to add the definitions for the `@slack/client` `RtmClient`.
